name: Continuous Deployment
 
on: 
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: SSH and deploy app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~/src/forum-api-v2
          git pull origin main
          export NVM_INC=/home/ubuntu/.nvm/versions/node/v22.11.0/include/node
          export NVM_DIR=/home/ubuntu/.nvm
          export NVM_CD_FLAGS=
          export NVM_BIN=/home/ubuntu/.nvm/versions/node/v22.11.0/bin
          source ~/.nvm/nvm.sh
          npm install
          npm run migrate up
          pm2 restart forum-api